-- Complete controlled Screen Assist doctrine for the four operational interfaces.
-- Additive only: no frozen governance entity, status or transition is modified.

WITH screens(role_name, screen_key, screen_title, purpose_text, controls_text) AS (
  VALUES
  -- Team Leader: frontline coordination and completion, not management triage.
  ('TEAM_LEADER','team_leader.my_work','My Work','This screen brings together the Team Leader tasks, acknowledgements and follow-ups requiring attention.','Open displays the linked source. Complete records work performed and evidence where required. It does not close the source governance concern.'),
  ('TEAM_LEADER','team_leader.dashboard','Team Leader Dashboard','This screen summarises today’s service-level work and matters the Team Leader needs to see.','Cards open their underlying lists. Counts describe recorded work; they are not clinical scores.'),
  ('TEAM_LEADER','team_leader.daily_governance','Daily Governance','This screen presents the published daily governance information relevant to the Team Leader’s service and responsibilities.','Open reads the governance item. Acknowledge records that it was seen. The Team Leader does not replace the Registered Manager’s governance decision.'),
  ('TEAM_LEADER','team_leader.signals','My Signals','This screen shows signals raised by the user or visible within the authorised service scope.','Open shows the factual signal and its status. New Signal starts factual capture. The Team Leader flags immediate action but does not select governance severity.'),
  ('TEAM_LEADER','team_leader.my_actions','My Actions','This screen lists governance actions assigned to the Team Leader with owners, due dates and evidence requirements.','Start updates work status. Add Evidence records what was done. Submit Completion sends evidence for management review; it does not certify effectiveness.'),
  ('TEAM_LEADER','team_leader.weekly_review','Weekly Review','This screen lets the Team Leader read and acknowledge the published service review relevant to their work.','Open reads the published review. Acknowledge records receipt. Editing or finalising the management review is not a Team Leader function.'),
  ('TEAM_LEADER','team_leader.escalations','Escalations','This screen shows escalations visible to the Team Leader and any assigned follow-up.','Open displays the authorised escalation details. Complete Assigned Work submits evidence; ownership and closure remain governed by the escalation workflow.'),
  ('TEAM_LEADER','team_leader.action_tracker','Action Tracker','This screen tracks service actions and their progress without treating completion as proof of effectiveness.','Filters change the visible list. Open shows source, owner and due date. Completion and effectiveness remain separate steps.'),
  ('TEAM_LEADER','team_leader.help','Help and Guidelines','This screen provides approved operational guidance targeted to the Team Leader role.','Search and article selection change only the displayed guidance. Help content cannot change governance records.'),

  -- Registered Manager: daily governance decision and closed-loop management.
  ('REGISTERED_MANAGER','registered_manager.my_work','My Work','This screen brings together Registered Manager reviews, decisions and follow-ups requiring attention.','Open follows the item to its source workflow. Completing a task does not bypass its evidence, review or closure gates.'),
  ('REGISTERED_MANAGER','registered_manager.daily_oversight','Daily Oversight','This is the Registered Manager’s daily governance workspace for new signals and monitored items due for reconsideration.','Monitor keeps active oversight and requires a review point. Create Action assigns work. Escalate starts higher time-bound oversight. Close requires rationale and preserves history.'),
  ('REGISTERED_MANAGER','registered_manager.risk_register','Risk Register','This screen records service-level governance risks, ownership, controls, review dates and trajectory.','Open shows evidence and history. Review Controls and Update Trajectory require an authorised human rationale.'),
  ('REGISTERED_MANAGER','registered_manager.strategic_oversight','Strategic Oversight','This view shows strategic-risk information available to the Registered Manager without changing Director or RI responsibilities.','Filters change scope. Open shows linked evidence. Promotion follows the existing guarded workflow and cannot be performed by Screen Assist.'),
  ('REGISTERED_MANAGER','registered_manager.interventions','Intervention Action','This screen manages structured interventions linked to supported governance evidence and intended outcomes.','Create or Update Intervention requires source, owner, review point and intended outcome. Screen Assist explains but never submits.'),
  ('REGISTERED_MANAGER','registered_manager.escalations','Escalations','This screen manages concerns moved into higher, time-bound oversight.','Open shows the source and history. Update Response records progress. Closure requires the applicable review, evidence and rationale.'),
  ('REGISTERED_MANAGER','registered_manager.action_tracker','Action Tracker','This screen oversees governance actions, ownership, deadlines, completion evidence and management review.','Open shows linked source and evidence. Return requests more work. Verify Completion does not automatically establish effectiveness.'),
  ('REGISTERED_MANAGER','registered_manager.weekly_review','Weekly Governance Review','This screen converts the week’s daily governance into a structured management reflection.','Draft assembles recorded evidence. Finalise locks the review version after the Registered Manager verifies what was known, done, learned and remains unresolved.'),
  ('REGISTERED_MANAGER','registered_manager.incidents','Serious Incidents','This screen manages the governance record and follow-up for serious incidents within authorised scope.','Open shows the incident governance record. Linked actions, escalation and reconstruction follow their existing workflows. Screen Assist gives no clinical interpretation.'),
  ('REGISTERED_MANAGER','registered_manager.reports','Reports','This screen provides approved operational governance reports from the frozen catalogue.','Select Report chooses a defined output. Scope and period control the included records. Generate does not create missing evidence.'),
  ('REGISTERED_MANAGER','registered_manager.pipeline','Governance Pipeline','This screen shows where governed items sit across the frozen signal-to-assurance pathway.','Stage selection filters the pipeline. Open follows an item to its authoritative record; the pipeline does not create a second lifecycle.'),
  ('REGISTERED_MANAGER','registered_manager.patterns','Systemic Patterns','This screen presents recurring evidence-linked themes requiring management review.','View Evidence opens contributors. Review Pattern records a human conclusion. Closure preserves the linked history.'),
  ('REGISTERED_MANAGER','registered_manager.effectiveness','Effectiveness','This screen tests whether completed actions achieved their intended outcome.','Record Effectiveness requires evidence and rationale. Screen Assist cannot choose Effective, Partly Effective or Not Effective.'),

  -- Director: organisation-level oversight.
  ('DIRECTOR','director.my_work','My Work','This screen lists Director-level assurance requests, reviews and follow-ups requiring attention.','Open follows the item to its authoritative record. The assistant cannot complete or approve work.'),
  ('DIRECTOR','director.dashboard','Strategic Dashboard','This screen provides organisation-level oversight of risks, escalations, actions, effectiveness and services requiring attention.','Cards and heat-map selections open underlying governance evidence. Download Reports opens the approved report catalogue.'),
  ('DIRECTOR','director.patterns','Systemic Patterns','This screen presents recurring themes within and across services for organisation-level review.','View Evidence opens contributing records. Review records rationale. Promotion uses the existing strategic-risk workflow.'),
  ('DIRECTOR','director.risks','Oversight Register','This screen provides Director oversight of organisation-level risks, controls, owners, review dates, trajectory and conclusions.','The Director may record an organisation-level control assessment or trajectory conclusion where those controls are displayed. Each requires evidence and rationale and does not replace the Registered Manager’s daily decision. The assistant cannot select a conclusion.'),
  ('DIRECTOR','director.effectiveness','Effectiveness','This screen gives the Director oversight of whether completed governance work achieved intended organisation-level outcomes.','View Evidence opens source actions and the Registered Manager’s effectiveness conclusion. The Director may challenge insufficient assurance or initiate an authorised organisation-level intervention, but cannot make or replace the operational effectiveness decision.'),
  ('DIRECTOR','director.interventions','Intervention Action','This screen manages organisation-level interventions linked to supported patterns or control failures.','Create and Update require source, owner, intended outcome and review point. The assistant remains read-only.'),
  ('DIRECTOR','director.rollup','Service Review Roll-up','This screen consolidates published service reviews without altering their source records.','Filters change the view. Open Review displays the signed source. The roll-up remains read-only.'),
  ('DIRECTOR','director.reconstruction','Governance Reconstruction','This screen reconstructs an evidence trail for an authorised scope and period.','Scope and date select existing evidence. Generate does not invent missing events or conclusions.'),
  ('DIRECTOR','director.escalations','Escalations','This screen oversees concerns under higher, time-bound accountability.','Open shows source and history. Escalate Further and Close require the existing authority, evidence and rationale.'),
  ('DIRECTOR','director.actions','Action Tracker','This screen provides organisation-level oversight of governance actions, ownership, deadlines and evidence.','Open shows source. Filters change scope. Completion remains separate from effectiveness.'),
  ('DIRECTOR','director.trends','Governance Trends','This screen describes recorded movement across services and themes.','Filters change period, service or theme. Open Evidence shows contributors. Trends are descriptive, not predictive.'),
  ('DIRECTOR','director.incidents','Serious Incidents','This screen provides organisation-level governance oversight of serious incidents and follow-up.','Open shows the governance record. The assistant cannot assess the incident clinically or advise treatment.'),
  ('DIRECTOR','director.reports','Reports','This screen provides the frozen catalogue of organisation-level governance and assurance reports.','Select, Scope and Generate control the approved output. Reports do not create new clinical conclusions.'),

  -- Responsible Individual: independent assurance; no operational execution.
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.my_work','My Work','This screen lists assurance reviews and queries requiring the Responsible Individual’s attention.','Open follows the item to its evidence. Respond records an assurance position where permitted; operational actions remain with operational roles.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.assurance','Board Assurance','This screen provides independent oversight of organisation-level governance evidence, risk movement, breaches and leadership conclusions.','Open Evidence reads the supporting trail. Raise Query requests clarification. The RI cannot perform operational governance actions while acting as RI.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.patterns','Systemic Patterns','This screen allows independent review of repeated themes and the leadership response.','View Evidence opens contributors. Raise Query requests assurance. Operational review, closure or promotion remains outside the RI capacity.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.effectiveness','Effectiveness','This screen lets the RI test whether leadership has evidenced that completed actions worked.','View Evidence is read-only. Record Assurance or Raise Query must not replace the operational effectiveness decision.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.interventions','Intervention Oversight','This screen shows interventions and whether leadership is monitoring their intended outcomes.','Open Evidence is read-only. Raise Query requests clarification. The RI does not create or manage the intervention while acting as RI.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.risks','Oversight Register','This screen gives the RI independent visibility of strategic risks, controls, trajectories and leadership conclusions.','Open and View Evidence are read-only. Raise Query records an assurance challenge. Risk operation and closure remain with authorised management.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.rollup','Service Review Roll-up','This screen consolidates published service reviews for independent assurance.','Filters change the read-only view. Open Review displays the signed source. The RI does not edit the review.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.reconstruction','Governance Reconstruction','This screen provides a reconstructable evidence trail for independent review.','Scope and date select existing records. Generate assembles evidence without changing it.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.escalations','Escalation Assurance','This screen shows whether significant concerns were escalated, owned, addressed and closed with evidence.','Open is read-only. Raise Query requests assurance. The RI does not own or close the escalation while acting as RI.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.actions','Action Assurance','This screen shows action ownership, timeliness, completion evidence and effectiveness for independent oversight.','Open Evidence is read-only. Raise Query requests clarification. The RI does not complete or verify operational actions.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.incidents','Serious Incident Assurance','This screen gives the Responsible Individual independent visibility of serious-incident governance, escalation, follow-up and recorded learning.','Open Evidence displays the governance trail. Acknowledge records that the incident was seen; it does not approve the operational response. The RI does not investigate clinically, manage the incident or replace operational ownership while acting as RI.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.trends','Governance Trends','This screen presents recorded movement across services and governance themes for independent assurance.','Filters change the evidence view. Open Evidence shows contributing records. Trends are descriptive, not predictive; the RI may challenge leadership conclusions but does not determine operational action.'),
  ('RESPONSIBLE_INDIVIDUAL','responsible_individual.reports','Assurance Reports','This screen provides approved RI and Board assurance reports from the frozen catalogue.','Select, Scope and Generate produce approved evidence views. The RI verifies the basis of conclusions and does not create missing evidence.')
), topics(topic, heading, question_examples) AS (
  VALUES
  ('purpose','What is this screen?',ARRAY['What is this screen?','What does this page show?']),
  ('role','What is my role here?',ARRAY['What is my role here?','What am I responsible for on this screen?']),
  ('use','How should I use it?',ARRAY['How do I use this screen?','Where should I start?']),
  ('controls','How do the controls work?',ARRAY['Explain the controls','What does this button do?','How do the filters work?']),
  ('next','What happens next?',ARRAY['What happens next?','Where does this information go?'])
)
INSERT INTO screen_assist_guidance
  (screen_key,topic,title,answer,steps,example_questions,target_roles,source_name,source_version,published,effective_from)
SELECT s.screen_key, t.topic, t.heading || ' — ' || s.screen_title,
  CASE t.topic
    WHEN 'purpose' THEN s.purpose_text
    WHEN 'role' THEN CASE s.role_name
      WHEN 'TEAM_LEADER' THEN 'Use this screen to coordinate frontline work, record factual information, complete assigned actions and provide evidence within Team Leader permissions. Management triage and assurance remain with their assigned roles.'
      WHEN 'REGISTERED_MANAGER' THEN 'Use this screen to conduct and evidence operational governance: review information, make authorised decisions, allocate work, monitor follow-through and test effectiveness.'
      WHEN 'DIRECTOR' THEN 'Use this screen for organisation-level oversight, cross-service learning and strategic governance. Review source evidence before recording a leadership conclusion.'
      ELSE 'Use this screen for independent assurance and challenge. While acting as Responsible Individual, you may review evidence and raise queries but must not perform operational governance actions.' END
    WHEN 'use' THEN 'Review the screen purpose, set the authorised scope, examine the displayed information, open the underlying evidence and use only the functions permitted to your active role. Record a rationale whenever the frozen workflow requires one.'
    WHEN 'controls' THEN s.controls_text
    ELSE CASE s.role_name
      WHEN 'RESPONSIBLE_INDIVIDUAL' THEN 'The evidence remains in its existing governance workflow. The RI may record an assurance position or raise a query where provided, but operational ownership and closure remain separate.'
      ELSE 'Any permitted decision or follow-up continues through the existing Ordin Core workflow with its current owner, deadlines, evidence and review gates. Screen Assist cannot submit it.' END
  END,
  CASE t.topic WHEN 'use' THEN '["Confirm the active role and screen purpose.","Set only the authorised scope.","Open and verify source evidence.","Use the permitted control and record required rationale."]'::jsonb ELSE '[]'::jsonb END,
  CASE WHEN t.topic='purpose' THEN ARRAY['What is this screen?','What does this page show?'] ELSE t.question_examples END,
  ARRAY[s.role_name], 'Ordin Core Controlled Screen Doctrine', '1.1.0', FALSE, NULL
FROM screens s CROSS JOIN topics t
ON CONFLICT (screen_key,topic,source_version) DO NOTHING;
