-- Stage 3: one durable queue for reviews generated by governance events.
BEGIN;

CREATE TABLE IF NOT EXISTS governance_review_obligations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  company_id UUID NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  obligation_type VARCHAR(50) NOT NULL CHECK (obligation_type IN
    ('ACTION_EFFECTIVENESS','RISK_POST_EFFECTIVENESS','POST_ESCALATION_RISK','PATTERN_REVIEW')),
  subject_type VARCHAR(30) NOT NULL CHECK (subject_type IN ('ACTION','RISK','ESCALATION','PATTERN')),
  subject_id UUID NOT NULL,
  source_action_id UUID REFERENCES risk_actions(id) ON DELETE CASCADE,
  source_risk_id UUID REFERENCES risks(id) ON DELETE CASCADE,
  source_escalation_id UUID REFERENCES escalations(id) ON DELETE CASCADE,
  source_cluster_id UUID REFERENCES signal_clusters(id) ON DELETE CASCADE,
  owner_id UUID REFERENCES users(id) ON DELETE SET NULL,
  owner_role VARCHAR(50),
  due_at TIMESTAMPTZ NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','COMPLETED','CANCELLED')),
  completed_at TIMESTAMPTZ,
  completed_by UUID REFERENCES users(id) ON DELETE SET NULL,
  completion_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_open_governance_review_obligation
  ON governance_review_obligations(company_id, obligation_type, subject_type, subject_id)
  WHERE status='OPEN';
CREATE INDEX IF NOT EXISTS idx_governance_review_obligations_due
  ON governance_review_obligations(company_id, status, due_at);

-- Existing completed actions awaiting a verdict become visible immediately. The due date honours
-- an existing scheduled date, otherwise completion is the point at which the review became due.
INSERT INTO governance_review_obligations
  (company_id, obligation_type, subject_type, subject_id, source_action_id, source_risk_id,
   owner_role, due_at, reason)
SELECT ra.company_id, 'ACTION_EFFECTIVENESS', 'ACTION', ra.id, ra.id, ra.risk_id,
       'REGISTERED_MANAGER', COALESCE(ra.effectiveness_due_at, ra.completed_at, NOW()),
       'Completed action requires an effectiveness decision.'
  FROM risk_actions ra
 WHERE ra.completed_at IS NOT NULL
   AND ra.effectiveness_outcome IS NULL
ON CONFLICT DO NOTHING;

COMMIT;
