export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  DIRECTOR: 'DIRECTOR',
  RESPONSIBLE_INDIVIDUAL: 'RESPONSIBLE_INDIVIDUAL',
  REGISTERED_MANAGER: 'REGISTERED_MANAGER',
  TEAM_LEADER: 'TEAM_LEADER'
} as const;

export type Role = typeof ROLES[keyof typeof ROLES];
